### ISSUE TITLE
CRF granularity is only .5 instead of .25

### ISSUE THREAD

**Issue by Uranite** [Nj0be/HandBrake-SVT-AV1-PSY#5]
To clarify, _at least_ on windows, and on x64, because I can't test other platforms

Reproduce steps:
1. Grab the handbrake gui from github releases, either portable or installed, I can reproduce the issue on both
2. Open a video
3. Switch the encoder to svt-av1-psy
4. Modify the CRF

**Comment by Nj0be** [comment]
Have you tried changing the "Constant Quality fractional granularity" to 0.25 on File->Settings->Advanced menu?
I tried on the arch linux build and both the ui and the actual value passed as an argument are correct. Maybe it's a Windows build problem.
Let me know, thank you very much for your work!

**Comment by Uranite** [comment]
Changing the "Constant Quality fractional granularity" works, are we supposed to do that to enable 0.25 granularity?

**Comment by Nj0be** [comment]
> Changing the "Constant Quality fractional granularity" works, are we supposed to do that to enable 0.25 granularity?

Yes, the option is there to enable more granularity for those who want it. Setting 0.25 as default isn't necessary imho, 1 or 0.5 is good. In any case, HandBrake made the choice.
