### ISSUE TITLE
photon-noise

### ISSUE THREAD

**Issue by trufo2** [Nj0be/HandBrake-SVT-AV1-PSY#9]
I put "photon-noise=25" in "advanced options" and it doesn't change a thing.
"film-grain=50" works fine but I prefer photon-noise.

**Comment by Nj0be** [comment]
Sorry for the late reply. I'll have a look at it as soon as I have time. Thanks for reporting.

**Comment by veryprogram** [comment]
`fgs-table` also doesn't work in Advanced Options

**Comment by lokobb** [comment]
I repeatedly tested multiple times, and after encoding the same file using av1-svt-psy, whatever the output size is big or small, there are many instances where areas with bright white sky and light blue color will have one or two squares that are completely different from the rest of the frame, but have a similar color, appearing at certain times.

**Comment by Nj0be** [comment]
> I put "photon-noise=25" in "advanced options" and it doesn't change a thing. "film-grain=50" works fine but I prefer photon-noise.

I finally had some time to look into the issue. Regarding photon-noise, as far as I can see, it is not supported by either svt-av1 or svt-av1-psy. It is not mentioned in the documentation, nor can it be found by searching the GitHub/GitLab repository. 

> `fgs-table` also doesn't work in Advanced Options

As for fgs-table, which should be supported, I need to investigate further. Apologies for the delay...

**Comment by lokobb** [comment]
i found a very good quality and no "square box" if setting under "23 quality", and i was tested 10 movie works very well!
i share to here hope u can try it too, or have some feedback, thank you!


For Good Quality source: crf-16 bitrate-21000
cpu-used=4;tile-columns=1;tile-rows=0;enable-keyframe-filtering=2;kf-max-dist=240;kf-min-dist=24;end-usage=q;crf=16;bitrate=9100;row-mt=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partitions=1;enable-angle-delta=1;enable-intra-edge-filter=1;enable-chroma-from-luma=1;enable-dist-wtd-comp=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partition-types=1;enable-intra-edge-filter=1;enable-order-hint=1;enable-tx64=1;enable-flip-idtx=1;enable-filter-intra=1;enable-smooth-intra=1;enable-paeth-intra=1;enable-cfl-intra=1;enable-diagonal-intra=1;enable-split-lossless=1;enable-pc=1;psy-rd=2.0;aq-mode=1;aq-strength=1.0;deblock=ultralight;tune=vmaf


FOR GAIN / NOISE    edit crf=23 (12 to 20 alao perfect)     bitrate= 9100 for noise  21000 for clean source
NOISE
cpu-used=4;tile-columns=1;tile-rows=0;enable-keyframe-filtering=2;kf-max-dist=240;kf-min-dist=24;end-usage=q;crf=23;bitrate=9100;row-mt=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partitions=1;enable-angle-delta=1;enable-intra-edge-filter=1;enable-chroma-from-luma=1;enable-dist-wtd-comp=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partition-types=1;enable-intra-edge-filter=1;enable-order-hint=1;enable-tx64=1;enable-flip-idtx=1;enable-filter-intra=1;enable-smooth-intra=1;enable-paeth-intra=1;enable-cfl-intra=1;enable-diagonal-intra=1;enable-split-lossless=1;enable-pc=1;psy-rd=2.0;aq-mode=3;aq-strength=1.5;deblock=ultralight;tune=vmaf

**Comment by Nj0be** [comment]
> i found a very good quality and no "square box" if setting under "23 quality", and i was tested 10 movie works very well! i share to here hope u can try it too, or have some feedback, thank you!
> 
> For Good Quality source: crf-16 bitrate-21000 cpu-used=4;tile-columns=1;tile-rows=0;enable-keyframe-filtering=2;kf-max-dist=240;kf-min-dist=24;end-usage=q;crf=16;bitrate=9100;row-mt=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partitions=1;enable-angle-delta=1;enable-intra-edge-filter=1;enable-chroma-from-luma=1;enable-dist-wtd-comp=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partition-types=1;enable-intra-edge-filter=1;enable-order-hint=1;enable-tx64=1;enable-flip-idtx=1;enable-filter-intra=1;enable-smooth-intra=1;enable-paeth-intra=1;enable-cfl-intra=1;enable-diagonal-intra=1;enable-split-lossless=1;enable-pc=1;psy-rd=2.0;aq-mode=1;aq-strength=1.0;deblock=ultralight;tune=vmaf
> 
> FOR GAIN / NOISE edit crf=23 (12 to 20 alao perfect) bitrate= 9100 for noise 21000 for clean source NOISE cpu-used=4;tile-columns=1;tile-rows=0;enable-keyframe-filtering=2;kf-max-dist=240;kf-min-dist=24;end-usage=q;crf=23;bitrate=9100;row-mt=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partitions=1;enable-angle-delta=1;enable-intra-edge-filter=1;enable-chroma-from-luma=1;enable-dist-wtd-comp=1;enable-rect-partitions=1;enable-ab-partitions=1;enable-ext-partition-types=1;enable-intra-edge-filter=1;enable-order-hint=1;enable-tx64=1;enable-flip-idtx=1;enable-filter-intra=1;enable-smooth-intra=1;enable-paeth-intra=1;enable-cfl-intra=1;enable-diagonal-intra=1;enable-split-lossless=1;enable-pc=1;psy-rd=2.0;aq-mode=3;aq-strength=1.5;deblock=ultralight;tune=vmaf

Thank you for the feedback, Lokobb. I’ll try those settings in my next encoding. I appreciate you sharing them. I’ll go ahead and close the issue for now, but feel free to open a new one if you discover anything else. Thanks again!
